### ISSUE TITLE
Add Cuneiform REST

### ISSUE THREAD

**Issue by stigviaene** [hopshadoop/hopsworksBackend#26]
Add REST API to enable:
* Getting Cuneiform job history
* Submitting a new Cuneiform job
* Monitoring a running Cuneiform job

**Comment by jimdowling** [comment]
REST API, I guess. No need for websockets here...

**Comment by stigviaene** [comment]
Well, I was thinking of putting job execution in a websocket session:
* Uploading a workflow file
* Inspecting it server-side, yielding unbound input and queryable output parameters
* Having the user define bindings for these parameters
* Starting the workflow
* Monitoring the progress of the job

Since you'd like immediate feedback on these actions, I think websockets make sense?

**Comment by jimdowling** [comment]
For me, websockets is mostly about (1) asynchronous feedback on things happening on the server, and (2) collaboration - somebody else updates something that you see immediately. I don't think (2) is relevant. So, for (1), you were previously using ajax and asynchronous beans. Does that not work now? Ajax and polling for a result would work. As would landing on a page and asking to load: load my most recent experiment (or load my ongoing experiments)? That would trigger the rest call. When you upload a workflow file and that succeeds, we can trigger another rest call to redraw the UI - or preferably just redraw the UI with whatever is returned from the load() call.
Monitoring the progress could be done with periodic ajax calls? 
If you can reuse the access control code for Vangelis' websockets server (projectName, sessionID -> valid ?), then sure it's ok. Although it seems like overkill.

**Comment by stigviaene** [comment]
Right, I didn't take into account the access control. Ajax polling should work just fine.
Updating the issue description.

**Comment by stigviaene** [comment]
Moved to hopshadoop/hopsworks#38
